### ISSUE TITLE
Boost library not included in project

### ISSUE THREAD

**Issue by sogoiii** [OculusRiftInAction/OculusRiftInAction#50]
Procedure:
1) make project with <code> cmake .. -G Xcode </code>
2) Open project with Xcode [I have 6.1.1]
3) Try to build one of the examples.

Xcode complains with <code>'boost/config.hpp' file not found</code> in <code> OculusRiftInAction/examples/cpp/common/Common.h:38</code>

System:
Xcode: 6.1.1
Yosemite: 10.10.1

**Comment by jherico** [comment]
fixed in c7b451cae6f63c5a1aee7f1de6f03ae6d4da114f
