### ISSUE TITLE
how to compile without Qt?

### ISSUE THREAD

**Issue by akosmaroy** [OculusRiftInAction/OculusRiftInAction#58]
Hi,

I'm having trouble compiling the whole source package with Qt5 on Linux, thus I'm trying to work my way around not having to use Qt. in the CMakeLists.txt file it actually says that:

```
# Qt is optional, but required to build the chapter 10 examples
```

but when I run cmake, I get an error when Qt is not found:

```
CMake Error at CMakeLists.txt:180 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!

```

thus, how do I compile without Qt?

Akos

**Comment by jherico** [comment]
The Qt stuff in the CMake file incorrectly listed it as required.  I've modified it, and you cna update, or you can just change line 180 of the CMakeLists.txt file in the root to remove 'REQUIRED' flag.

**Comment by akosmaroy** [comment]
thanks for the quick fix, but now I get:

```
CMake Error at CMakeLists.txt:180 (find_package):
  find_package called with invalid argument "Core"
```

I guess this might work:

```
find_package(Qt5 QUIET)
```

?

**Comment by jherico** [comment]
I can't test it right now, as Im at work.  However, you'd still need the
'components' part of the find_package for it not to break for people who
are compiling with Qt.

**Comment by jherico** [comment]
How do you have the Rift display set up in X?  Is it set up as a separate X screen?  If so, you need to make sure that you set the DISPLAY variable before running an example app.  Again, I'll take a look at this as soon as I have a chance so I can see how it behaves on Linux at this point (although my primary Linux system is Mint).

**Comment by akosmaroy** [comment]
no, it's an extension of my main display. either way, when starting a (windowed) app, I'd expect a window to appear 'somewhere', but nothing appears.

thank you for looking into this

**Comment by jherico** [comment]
OK, I've identified an issue with the resource code that was causing a crash, as well as modifed how Qt is detected so that it locates all the componets properly, but doesn't require Qt.  The code has been submitted in a pull request  here:  https://github.com/jherico/OculusRiftInAction so one of my co-authors can review the code.  If you want to try it out before that happens you can clone my development fork from here:  https://github.com/jherico/OculusRiftInAction

Please re-open if this doesn't resolve your issues.

**Comment by akosmaroy** [comment]
confirmed - the jherico/OculusRiftInAction  latest head builds out of the box on ubuntu without Qt
