### ISSUE TITLE
Example 8 build failure, oria::renderCubeScene undefined

### ISSUE THREAD

**Issue by pizthewiz** [OculusRiftInAction/OculusRiftInAction#62]
Both _Example_8_TextureSize_ and _Example_8_AsyncTimewarp_ seem to call the `renderCubeScene` function though it doesn't appear to be defined in the `oria` namespace (or anywhere else?).

[Example_8_TextureSize.cpp#L74](https://github.com/OculusRiftInAction/OculusRiftInAction/blob/0b84f85b64626c49c05d26b48b92e8bb14316261/examples/cpp/Example_8_TextureSize.cpp#L74):
```c++
    mv.withPush([&]{
      mv.postMultiply(glm::inverse(player));
      oria::renderCubeScene(ipd, eyeHeight);
    });
```

[Example_8_AsyncTimewarp.cpp#L229](https://github.com/OculusRiftInAction/OculusRiftInAction/blob/0b84f85b64626c49c05d26b48b92e8bb14316261/examples/cpp/Example_8_AsyncTimewarp.cpp#L229):
```c++
    mv.withPush([&]{
      mv.postMultiply(glm::inverse(player));
      oria::renderCubeScene(ipd, eyeHeight);
    });
```

**Comment by jherico** [comment]
Sorry about that.  

That function has been renamed oria::renderExampleScene(), but the last merge from my development fork didn't have the change in all the examples.  It should be fixed in the next merge.  You can build by making the change locally in the mean time.

**Comment by pizthewiz** [comment]
Great thanks for the fix and sorry I didn't notice the similarly named/signature'd method!

**Comment by jherico** [comment]
this should be fixed now.
