### ISSUE TITLE
Optional dependencies

### ISSUE THREAD

**Issue by calvinkang** [OculusRiftInAction/OculusRiftInAction#67]
Could you tell me how to link the Qt dependancies in the cmake configuration?
I assigned the path to the Qt 5.4 but the cmake shows Qt5_DIR-NOTFOUND
How can I do to solve it?

**Comment by jherico** [comment]
CMake can find Qt in a variety of ways. First, you should make sure you have a reasonably recent version of CMake.  I believe some of the older pre-3.x versions had issues.

On my system, CMake will discover the Qt library if the Qt binaries are in the path environment variable.  On my system that means the directory `C:\Qt\5.4\msvc2013_opengl\bin`

CMake will also discover Qt if I set the QT5_DIR to point at the Qt cmake files location.  On my system that translates to the following command:

`set QT5_DIR=c:\Qt\5.4\msvc2013_opengl\lib\cmake`

**Comment by jherico** [comment]
closing, please reopen if this is still blocking you.
