### ISSUE TITLE
CMake errors on project files creation

### ISSUE THREAD

**Issue by ingdestino** [OculusRiftInAction/OculusRiftInAction#84]
I'm trying to build the examples on a Windows 8 (64bit) machine.
I've downloaded the code and installed CMake 3.2.1 for Windows.
I've followed the instructions, setting OculusRiftInAction main folder as source folder and newly created OculusRiftInAction/build as build folder.

Running CMake I got some errors: originally the issue seemed to be related to "pthread" missing dlls/libs/includes. 
But even after having retrieved and installed pthread stuff from https://www.sourceware.org/pthreads-win32/ , still errors occur.

This is the current output of CMake:

~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-

C:\Users\INGD\OculusRift\demos\OculusRiftInAction\build>"C:\Program Files (x86)\CMake\bin\cmake.exe" "C:/Users/INGD/OculusRift/demos/OculusRiftInAction"
-- Building for: Visual Studio 12 2013
-- The C compiler identification is MSVC 18.0.31101.0
-- The CXX compiler identification is MSVC 18.0.31101.0
-- Check for working C compiler using: Visual Studio 12 2013
-- Check for working C compiler using: Visual Studio 12 2013 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 12 2013
-- Check for working CXX compiler using: Visual Studio 12 2013 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Release build, resources will be loaded from executable/bundle
CMake Error at CMakeLists.txt:49 (set_target_properties):
  set_target_properties Can not find target to add properties to: OculusVR

-- Found OpenGL: opengl32
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Using Win32 for window creation
-- Using WGL for context creation
-- OpenCV NOT found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - failed
-- Looking for fseeko
-- Looking for fseeko - not found
-- Looking for unistd.h
-- Looking for unistd.h - not found
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
-- Performing Test COMPILER_HAS_DEPRECATED
-- Performing Test COMPILER_HAS_DEPRECATED - Success
Making executable Example_2_1_SDK in folder Examples
Making executable Example_2_2_Tracker in folder Examples
Making executable Example_2_3_Display in folder Examples
Making executable Example_2_4_HelloRift in folder Examples
Making executable Example_3_3_Tracker in folder Examples
Making executable Example_3_5_TrackerPrediction in folder Examples
Making executable Example_4_3_0_Undistorted in folder Examples
Making executable Example_4_3_1_Distorted in folder Examples
Making executable Example_5_1_Monoscopic in folder Examples
Making executable Example_5_2_Stereoscopic in folder Examples
Making executable Example_5_3_RiftRendered in folder Examples
Making executable Example_5_4_RiftSensors in folder Examples
Making executable Example_6_TextureSize in folder Examples
Making executable Example_SelfContained in folder Examples
-- Configuring incomplete, errors occurred!
See also "C:/Users/INGD/OculusRift/demos/OculusRiftInAction/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/INGD/OculusRift/demos/OculusRiftInAction/build/CMakeFiles/CMakeError.log".

~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-

As you  can see, other include file are missing.
Any idea on how to overcome this issue? Thanks

PS: I've seen that some recent post related to similar issues are reported at "OculusRiftInAction" forum at Manning Pubblications site.

**Comment by jherico** [comment]
The issue is actually unrelated to pthreads, but is instead 'set_target_properties Can not find target to add properties to: OculusVR'

This should be corrected by the latest merge.  please try updating the code with a 'git pull', 'git rebase' and 'git submodule update' and see if that corrects the problem.

**Comment by ingdestino** [comment]
Thanks, now configuration and generation are performed without errors. Many thanks again!
