### ISSUE TITLE
Problem running cmake

### ISSUE THREAD

**Issue by HappyCamperPC** [OculusRiftInAction/OculusRiftInAction#91]
I've created the build directory but when I type cmake .., cmake -h,  or cmake .. -G "Visual Studio" from within that directory I get an error message stating that "'cmake' is not recognized as an internal or external command, operable program or batch file.". If I go up one level to the OculusRiftInAction folder and try it I get the same error message.
If I press Windows Key R to open the Run window and type cmake .. I get another error message saying that Windows cannot find 'cmake'. What am I missing?

**Comment by jherico** [comment]
CMake is a utility for creating project files from a CMakeLists.txt meta-project descriptor file.  You need to download and install cmake from here:  https://cmake.org/

If you've installed it but the command still isn't working it's possible that it's simply not on your executable path.  You can either fix this by adding the folder where the cmake binary is installed (usually that would be `C:\Program Files (x86)\CMake\bin`) to your PATH environment variable or you can type our the full path to the command when running the cmake command, i.e. `C:\Program Files (x86)\CMake\bin\cmake.exe`

**Comment by HappyCamperPC** [comment]
Thanks for your rapid reply. I've downloaded cmake now and checked that it's in the Path. However I still get the same error message when typing cmake .., cmake -h or cmake .. -G "Visual Studio" in the command prompt. I've tried typing it in the C: directory  and the OculusRiftInAction directory and the build directory.
When a press Windows Key R and type cmake -h something flashes by in the command prompt window but too fast to read.

**Comment by AlexBenton** [comment]
Try running 'cmd', to bring up a command prompt, and then try running cmake
in the command prompt.  That will slow down the message so you can read it.
If it works, you probably just need to restart Visual Studio.  If it
doesn't work, then cmake is not on your path.

**Comment by HappyCamperPC** [comment]
That worked, thanks. So is the command to build it just cmake .. -G "Visual Studio 14"? Will that put it in the Build directory I made earlier in the OculusRiftInAction directory?

**Comment by jherico** [comment]
it will put it in whatever directory from which you run the cmake command.  If you're running `cmake ..` because you're currently in the build directory as per the instructions, then yes, that's where the project files should be,
