### ISSUE TITLE
'noexcept' : unknown override specifier	

### ISSUE THREAD

**Issue by nitinmaru** [OculusRiftInAction/OculusRiftInAction#97]
hI
i AM FACING ERROR OF NOEXCEPT

**Comment by nitinmaru** [comment]
i HAVE REFERRED http://stackoverflow.com/questions/18387640/how-to-deal-with-noexcept-in-visual-studio FOR SOLUTION BUT IT SEEMS SOMETHING i AM MISSING 

PLEASE HELP FOR SAME

**Comment by nitinmaru** [comment]
I found that error is related Oglplus libraries and supporting problem with c++11

**Comment by nitinmaru** [comment]
i am having stuck with this error please provide some kind of feedback
Looking forward fro your help

**Comment by AlexBenton** [comment]
I'm sorry but Visual C++ errors and C++ language keywords are beyond the
scope of our support for our book on the Oculus Rift.
