### ISSUE TITLE
Where is the Xcode project file?

### ISSUE THREAD

**Issue by jamesalliban** [OculusRiftInAction/OculusRiftInAction#98]
Running cmake .. in the build folder does not produce an Xcode project file. I'm following the instructions in the book very carefully and have tried lots of alternative approaches. The resulting folder structure looks like this:

![screen shot 2016-02-04 at 00 29 38](https://cloud.githubusercontent.com/assets/541677/12801696/8c34868a-cad6-11e5-8fd4-8a0bc0c71b43.png)

The final build file is only 1.9MB so it appears that the files are not being moved properly. Where could I be going wrong?

Setup details OSX 10.10, cmake 3.4.0, Oculus SDK 0.5.0.1-beta

**Comment by jherico** [comment]
CMake will, by default, produce a Makefile on OSX, not an XCode project.  Delete the contents of your build directory (in particular the `CMakeCache.txt`) and re-run cmake with the `-G` command.  This will tell you the list of available project generators, of which one should be `XCode` or `Xcode`.  I can't recall the capitalization, but matters. 

Additionally, the build directory will only contain the project files and the CMake generated files, so 1.9 MB is reasonable until you build.  After that it will contain the files produced by the project itself and should be significantly bigger.

**Comment by jamesalliban** [comment]
Thanks for the quick answer. Just tried and it works. I'm sure I tried this earlier but must have got caught on the spelling.
